### ISSUE TITLE
Bug? UI buttons don't show up after refresh

### ISSUE THREAD

**Issue by jsjoeio** [jacobherrington/conventional-comments-browser-extension#11]
This is super cool! So I think there's a bug where it shows up the first time you go to the Files tab on a PR but if you refresh the page, the UI buttons don't show up?

https://user-images.githubusercontent.com/3806031/136441341-2ab0a29c-c4c7-47e6-8bdb-feeff4be2c44.mov

**Comment by jacobherrington** [comment]
Yeah, that has to do with GitHub's method for reloading those tabs. It's not actually a page load (if I'm remembering right).

This line Is supposed to take care of that, but I've noticed its touch and go:
https://github.com/jacobherrington/conventional-comments-browser-extension/blob/036c99c1beafbee02b3bc579f153015cec7f9bd8/src/main.js#L1

I'm open to suggestions!

**Comment by jsjoeio** [comment]
> Yeah, that has to do with GitHub's method for reloading those tabs. It's not actually a page load (if I'm remembering right).

Ahhh got it!

> It seems like that event doesn't fire on a true page load, but if we're not listening for that event, the extension doesn't fire when I go from the Conversation tab to the Files changed tab.

Hmm...thinking out loud here. I guess there are two ways someone might get to the `Files changed tab`

1. Go there directly i.e. https://github.com/microsoft/vscode/pull/134586/files
2. Go to PR > click `Files changed tab`

Without having a ton of Chrome extension experience (I've built 1-2), I'm thinking it would be great if we could load your extension in both scenarios. How? Listen for:
1. URL change -> if URL changes & new URL contains regex (pseudo code) `github.com/something/something/pull/something/files` 
2. page load -> same condition as above

Helpful links:
- [How to listen for url change with Chrome Extension](https://stackoverflow.com/questions/34957319/how-to-listen-for-url-change-with-chrome-extension)
- [WIndow: hashchange event](https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event) 

Thoughts?
